2021-05-19T11:47:35.526454+00:00 heroku[web.1]: Restarting
2021-05-19T11:47:35.530846+00:00 heroku[web.1]: State changed from up to starting
2021-05-19T11:47:37.250674+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2021-05-19T11:47:37.327234+00:00 app[web.1]: [2021-05-19 11:47:37 +0000] [18] [INFO] Worker exiting (pid: 18)
2021-05-19T11:47:37.327244+00:00 app[web.1]: [2021-05-19 11:47:37 +0000] [17] [INFO] Worker exiting (pid: 17)
2021-05-19T11:47:37.344362+00:00 app[web.1]: [2021-05-19 11:47:37 +0000] [4] [INFO] Handling signal: term
2021-05-19T11:47:37.369708+00:00 app[web.1]: [2021-05-19 11:47:37 +0000] [4] [WARNING] Worker with pid 18 was terminated due to signal 15
2021-05-19T11:47:37.377703+00:00 app[web.1]: [2021-05-19 11:47:37 +0000] [4] [WARNING] Worker with pid 17 was terminated due to signal 15
2021-05-19T11:47:37.445196+00:00 app[web.1]: [2021-05-19 11:47:37 +0000] [4] [INFO] Shutting down: Master
2021-05-19T11:47:38.042589+00:00 heroku[web.1]: Process exited with status 0
2021-05-19T11:47:47.298219+00:00 heroku[web.1]: Starting process with command `gunicorn app_run:app --preload`
2021-05-19T11:47:54.000000+00:00 app[api]: Build succeeded
2021-05-19T11:47:56.096454+00:00 app[web.1]: [2021-05-19 11:47:56 +0000] [4] [INFO] Starting gunicorn 20.1.0
2021-05-19T11:47:56.097131+00:00 app[web.1]: [2021-05-19 11:47:56 +0000] [4] [INFO] Listening at: http://0.0.0.0:46419 (4)
2021-05-19T11:47:56.097196+00:00 app[web.1]: [2021-05-19 11:47:56 +0000] [4] [INFO] Using worker: sync
2021-05-19T11:47:56.104625+00:00 app[web.1]: [2021-05-19 11:47:56 +0000] [17] [INFO] Booting worker with pid: 17
2021-05-19T11:47:56.119461+00:00 app[web.1]: [2021-05-19 11:47:56 +0000] [18] [INFO] Booting worker with pid: 18
2021-05-19T11:47:56.617252+00:00 heroku[web.1]: State changed from starting to up
2021-05-19T11:48:21.205505+00:00 app[web.1]: [2021-05-19 11:48:21,203] ERROR in app: Exception on /callback [POST]
2021-05-19T11:48:21.205531+00:00 app[web.1]: Traceback (most recent call last):
2021-05-19T11:48:21.205532+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2051, in wsgi_app
2021-05-19T11:48:21.205532+00:00 app[web.1]: response = self.full_dispatch_request()
2021-05-19T11:48:21.205533+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1501, in full_dispatch_request
2021-05-19T11:48:21.205533+00:00 app[web.1]: rv = self.handle_user_exception(e)
2021-05-19T11:48:21.205533+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1499, in full_dispatch_request
2021-05-19T11:48:21.205533+00:00 app[web.1]: rv = self.dispatch_request()
2021-05-19T11:48:21.205533+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1485, in dispatch_request
2021-05-19T11:48:21.205534+00:00 app[web.1]: return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2021-05-19T11:48:21.205534+00:00 app[web.1]: File "/app/app_run.py", line 47, in callback
2021-05-19T11:48:21.205534+00:00 app[web.1]: events = handler.parser(body, signature)
2021-05-19T11:48:21.205535+00:00 app[web.1]: TypeError: 'WebhookParser' object is not callable
2021-05-19T11:48:21.207635+00:00 app[web.1]: 10.52.10.57 - - [19/May/2021:11:48:21 +0000] "POST /callback HTTP/1.1" 500 290 "-" "LineBotWebhook/2.0"
2021-05-19T11:48:21.208199+00:00 heroku[router]: at=info method=POST path="/callback" host=agile-island-66575.herokuapp.com request_id=7ccc4bb4-ffee-4221-b4ac-69c0312b0c06 fwd="147.92.150.193" dyno=web.1 connect=0ms service=7ms status=500 bytes=463 protocol=https
2021-05-19T11:53:46.000000+00:00 app[api]: Build started by user ttt8314@gmail.com
2021-05-19T11:54:36.099503+00:00 app[api]: Release v17 created by user ttt8314@gmail.com
2021-05-19T11:54:36.099503+00:00 app[api]: Deploy 9d325cf4 by user ttt8314@gmail.com
2021-05-19T11:54:36.267067+00:00 heroku[web.1]: Restarting
2021-05-19T11:54:36.279851+00:00 heroku[web.1]: State changed from up to starting
2021-05-19T11:54:37.600599+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2021-05-19T11:54:37.693478+00:00 app[web.1]: [2021-05-19 11:54:37 +0000] [17] [INFO] Worker exiting (pid: 17)
2021-05-19T11:54:37.694027+00:00 app[web.1]: [2021-05-19 11:54:37 +0000] [4] [INFO] Handling signal: term
2021-05-19T11:54:37.694439+00:00 app[web.1]: [2021-05-19 11:54:37 +0000] [18] [INFO] Worker exiting (pid: 18)
2021-05-19T11:54:38.095415+00:00 app[web.1]: [2021-05-19 11:54:38 +0000] [4] [INFO] Shutting down: Master
2021-05-19T11:54:38.418628+00:00 heroku[web.1]: Process exited with status 0
2021-05-19T11:54:46.939326+00:00 heroku[web.1]: Starting process with command `gunicorn app_run:app --preload`
2021-05-19T11:54:55.000000+00:00 app[api]: Build succeeded
2021-05-19T11:54:57.223148+00:00 app[web.1]: [2021-05-19 11:54:57 +0000] [4] [INFO] Starting gunicorn 20.1.0
2021-05-19T11:54:57.223857+00:00 app[web.1]: [2021-05-19 11:54:57 +0000] [4] [INFO] Listening at: http://0.0.0.0:22555 (4)
2021-05-19T11:54:57.223951+00:00 app[web.1]: [2021-05-19 11:54:57 +0000] [4] [INFO] Using worker: sync
2021-05-19T11:54:57.231425+00:00 app[web.1]: [2021-05-19 11:54:57 +0000] [17] [INFO] Booting worker with pid: 17
2021-05-19T11:54:57.267233+00:00 app[web.1]: [2021-05-19 11:54:57 +0000] [18] [INFO] Booting worker with pid: 18
2021-05-19T11:54:57.288263+00:00 heroku[web.1]: State changed from starting to up
2021-05-19T11:55:37.506485+00:00 app[web.1]: [2021-05-19 11:55:37,504] ERROR in app: Exception on /callback [POST]
2021-05-19T11:55:37.506521+00:00 app[web.1]: Traceback (most recent call last):
2021-05-19T11:55:37.506522+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2051, in wsgi_app
2021-05-19T11:55:37.506522+00:00 app[web.1]: response = self.full_dispatch_request()
2021-05-19T11:55:37.506523+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1501, in full_dispatch_request
2021-05-19T11:55:37.506523+00:00 app[web.1]: rv = self.handle_user_exception(e)
2021-05-19T11:55:37.506523+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1499, in full_dispatch_request
2021-05-19T11:55:37.506524+00:00 app[web.1]: rv = self.dispatch_request()
2021-05-19T11:55:37.506524+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1485, in dispatch_request
2021-05-19T11:55:37.506524+00:00 app[web.1]: return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2021-05-19T11:55:37.506524+00:00 app[web.1]: File "/app/app_run.py", line 47, in callback
2021-05-19T11:55:37.506525+00:00 app[web.1]: eve = parser.parser(body, signature)
2021-05-19T11:55:37.506525+00:00 app[web.1]: AttributeError: 'WebhookParser' object has no attribute 'parser'
2021-05-19T11:55:37.509540+00:00 app[web.1]: 10.63.65.212 - - [19/May/2021:11:55:37 +0000] "POST /callback HTTP/1.1" 500 290 "-" "LineBotWebhook/2.0"
2021-05-19T11:55:37.513779+00:00 heroku[router]: at=info method=POST path="/callback" host=agile-island-66575.herokuapp.com request_id=8c0db196-7137-4166-9e42-c3c64a750de6 fwd="147.92.150.195" dyno=web.1 connect=1ms service=13ms status=500 bytes=463 protocol=https
2021-05-19T11:59:21.000000+00:00 app[api]: Build started by user ttt8314@gmail.com
2021-05-19T12:00:10.903979+00:00 app[api]: Deploy 5d2e9871 by user ttt8314@gmail.com
2021-05-19T12:00:10.903979+00:00 app[api]: Release v18 created by user ttt8314@gmail.com
2021-05-19T12:00:16.911808+00:00 heroku[web.1]: Restarting
2021-05-19T12:00:16.984918+00:00 heroku[web.1]: State changed from up to starting
2021-05-19T12:00:18.031721+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2021-05-19T12:00:18.100076+00:00 app[web.1]: [2021-05-19 12:00:18 +0000] [17] [INFO] Worker exiting (pid: 17)
2021-05-19T12:00:18.100437+00:00 app[web.1]: [2021-05-19 12:00:18 +0000] [4] [INFO] Handling signal: term
2021-05-19T12:00:18.101147+00:00 app[web.1]: [2021-05-19 12:00:18 +0000] [18] [INFO] Worker exiting (pid: 18)
2021-05-19T12:00:18.501903+00:00 app[web.1]: [2021-05-19 12:00:18 +0000] [4] [INFO] Shutting down: Master
2021-05-19T12:00:18.816595+00:00 heroku[web.1]: Process exited with status 0
2021-05-19T12:00:30.000000+00:00 app[api]: Build succeeded
2021-05-19T12:00:34.544692+00:00 heroku[web.1]: Starting process with command `gunicorn app_run:app --preload`
2021-05-19T12:00:48.324178+00:00 app[web.1]: Matplotlib is building the font cache; this may take a moment.
2021-05-19T12:00:55.874880+00:00 app[web.1]: [2021-05-19 12:00:55 +0000] [4] [INFO] Starting gunicorn 20.1.0
2021-05-19T12:00:55.876864+00:00 app[web.1]: [2021-05-19 12:00:55 +0000] [4] [INFO] Listening at: http://0.0.0.0:53886 (4)
2021-05-19T12:00:55.877117+00:00 app[web.1]: [2021-05-19 12:00:55 +0000] [4] [INFO] Using worker: sync
2021-05-19T12:00:55.890298+00:00 app[web.1]: [2021-05-19 12:00:55 +0000] [17] [INFO] Booting worker with pid: 17
2021-05-19T12:00:55.965433+00:00 app[web.1]: [2021-05-19 12:00:55 +0000] [18] [INFO] Booting worker with pid: 18
2021-05-19T12:00:56.318882+00:00 heroku[web.1]: State changed from starting to up
2021-05-19T12:00:57.361591+00:00 app[web.1]: [2021-05-19 12:00:57,359] ERROR in app: Exception on /callback [POST]
2021-05-19T12:00:57.361650+00:00 app[web.1]: Traceback (most recent call last):
2021-05-19T12:00:57.361651+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2051, in wsgi_app
2021-05-19T12:00:57.361652+00:00 app[web.1]: response = self.full_dispatch_request()
2021-05-19T12:00:57.361652+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1502, in full_dispatch_request
2021-05-19T12:00:57.361653+00:00 app[web.1]: return self.finalize_request(rv)
2021-05-19T12:00:57.361653+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1521, in finalize_request
2021-05-19T12:00:57.361654+00:00 app[web.1]: response = self.make_response(rv)
2021-05-19T12:00:57.361654+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1684, in make_response
2021-05-19T12:00:57.361655+00:00 app[web.1]: raise TypeError(
2021-05-19T12:00:57.361655+00:00 app[web.1]: TypeError: The view function for 'callback' did not return a valid response. The function either returned None or ended without a return statement.
2021-05-19T12:00:57.370429+00:00 app[web.1]: 10.171.230.57 - - [19/May/2021:12:00:57 +0000] "POST /callback HTTP/1.1" 500 290 "-" "LineBotWebhook/2.0"
2021-05-19T12:00:57.370974+00:00 heroku[router]: at=info method=POST path="/callback" host=agile-island-66575.herokuapp.com request_id=308c5199-816a-4da4-b932-5dd8cc691390 fwd="147.92.149.168" dyno=web.1 connect=0ms service=25ms status=500 bytes=463 protocol=https
